### ISSUE TITLE
Aspnet5 RC1 support

### ISSUE THREAD

**Issue by jarroda** [ryan1234/ThinktectureDocker#1]
I would like to update this dockerfile to run IS3 on RC1.  Do you know if the two workarounds for mono bugs are still required?  I noticed one of the issues [168](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/168) had been closed, but I'm not sure how the resolution of it impacts this dockerfile.

**Comment by ryan1234** [comment]
I've actually changed companies since writing this and before I left the last company we phased out IS3 completely. =(

But I believe you are right. At least one of the Mono bugs has been resolved. I wouldn't be surprised if the other was resolved as well.

Sorry that probably doesn't help you all that much.

**Comment by jarroda** [comment]
No problem, I know how that goes.  I just found your blog post on running IS3 in mono, so between that and this docker container, you've already helped me alot.  Thanks!
